<a href="https://colab.research.google.com/github/qkrsj/AI-PROGRAMMING/blob/main/Week-01/NUMPY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# numpy
# np.array()로 생성(list, tuple 넣는다)
# ML 에러, 폭망 주요 원인  a,ndim : 차원 / a.shape : 모양 / a.dtype : 자료형

import numpy as np

data1 = [1,2,3,4,5,6]
data2 = [{10,20,30},{40,50,60}]

a = np.array(data1)
print(data1)
print(a)
print(a.shape)
# Python 문법상 요소가 1개인 튜플은 반드시 뒤에 ,를 포함해야 합니다
# 6개의 칸을 가진 1차원 공간의 형태
print(a.ndim)
print(a.dtype)
print(a*-1)
print(a+a)

b = np.array(data2)
print(b)
print(b.shape)
print(b.ndim)
print(b.dtype)

[1, 2, 3, 4, 5, 6]
[1 2 3 4 5 6]
(6,)
1
int64
[-1 -2 -3 -4 -5 -6]
[ 2  4  6  8 10 12]
[{10, 20, 30} {40, 50, 60}]
(2,)
1
object


In [ ]:
np.zeros(10)    # 0으로 이루어진 array
np.ones((2,3))    # 1로 이루어진 array
np.arange(10)   # range 0~9
arr = np.array([1.2, 3.4, -0.9, -2.1, 100.])
arr_int = arr.astype(np.int32)
print(arr_int)
num_str = np.array(['1.234', '-2.29', '1000'], dtype = np.bytes_)
num = num_str.astype(float)
print(num)
print(num.dtype)

[  1   3   0  -2 100]
[   1.234   -2.29  1000.   ]
float64


In [ ]:
data1 = np.array([[110,120,130],[140,150,160]])
data2 = np.array([[10,20,30],[40,50,60]])

data1 * data2

array([[1100, 2400, 3900],
       [5600, 7500, 9600]])

In [ ]:
a = np.array([1,2,3])
b = np.array([4,5,6])

c = a + b
d = a * b
e = a + 1

In [ ]:
a = np.array([1,2,3])
b = np.sum(a)
c = np.mean(a)
d = np.min(a)
e = np.max(a)


In [ ]:
data1 = [1,2,3,4,5,6]

a = np.array([data1])
print(a[3:5])

[]


In [ ]:
data2 = np.array([[1.2],[3.4],[5,6]])
print(data2[:.0])

[1,3,5]

In [ ]:
data1 = np.array([[1,2,3],[4,5,6]])
data2 = np.array([[1,2],[3,4],[5,6]])

print(data1)
print(data2)
print(np.dot(data1,data2))

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]
[[22 28]
 [49 64]]


In [ ]:
data1 = np.array([[1,2,3],[4,5,6]])

print(data1)
print(np.sum(data1))
print(np.sum(data1, axis = 0)) # axis 0: 행(row) 방향으로 동작 (위에서 아래로).
print(np.sum(data1, axis = 1)) # axis 1: 열(column) 방향으로 동작 (왼쪽에서 오른쪽으로)

print(np.mean(data1))
print(np.mean(data1, axis = 0))
print(np.mean(data1, axis = 1))

print(np.min(data1))
print(np.min(data1, axis = 0))
print(np.min(data1, axis = 1))

# argmax 가장 많이 쓰임, 생성형 AI
print(np.argmax(data1))
print(np.argmax(data1, axis = 0))  # axis=0: 각 열에서 가장 큰 값의 행 번호를 찾음
print(np.argmax(data1, axis = 1))  # axis=1: 각 행에서 가장 큰 값의 열 번호를 찾음

[[1 2 3]
 [4 5 6]]
21
[5 7 9]
[ 6 15]
3.5
[2.5 3.5 4.5]
[2. 5.]
1
[1 2 3]
[1 4]
5
[1 1 1]
[2 2]


In [ ]:
data1 = np.array([[1,2,3],[4,5,6]])
print(data1)
print(data1.shape)
data2 = data1.reshape(3,2)
print(data2)
print(data2.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)
[[1 2]
 [3 4]
 [5 6]]
(3, 2)


In [ ]:
data1= np.array([1,2,3,4,5,6,7,8])

newarr = data1.reshape(2,-1)  # -1은 알아서 붙이라는 뜻
newarr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
# flatten 매우 중요
# EX) 차량 번호판, 간단한 이미지 인식
data1 = [1,2,3,4,5,6]
a = np.array(data1)
print(a)
a = a.reshape(2,3)
print(a)
a = a.flatten()
print(a)


[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [ ]:
# 합치기
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.concatenate((arr1,arr2))
print(arr)

[1 2 3 4 5 6]


In [ ]:
arr1 = np.array(([1,2],[3,4]))
arr2 = np.array(([5,6],[7,8]))
arr = np.concatenate((arr1,arr2), axis=1)
print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.stack((arr1,arr2), axis=1)
print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [ ]:
#쪼개기

arr =np.array([1,2,3,4,5,6])
newarr = np.array_split(arr,3)
print(newarr)

arr = np.array([[1,2],[3,4],[5,6],[7,8],[9,10],[11,12]])
newarr = np.array_split(arr,3)
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]
[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [ ]:
a = np.array([[1,3,5],[2,4,6],[3,6,9]])
print(np.max(a, axis = 0))
print(np.min(a, axis = 1))

print(np.argmax(a, axis = 0))  # argmax 특징 찾기
print(np.argmax(a, axis = 1))


[3 6 9]
[1 2 3]
[2 2 2]
[2 2 2]
